services:
  - type: web
    name: computer-science-a-level-programming
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate --noinput
    startCommand: gunicorn my_website.wsgi:application
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: DJANGO_DEBUG
        value: "False"
