# Generated by Django 5.2.4 on 2025-11-23 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pastpapers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="answer_text",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="question",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="pastpapers/questions/%Y/%m/%d/"
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="difficulty",
            field=models.CharField(
                choices=[("easy", "Easy"), ("medium", "Medium"), ("hard", "Hard")],
                default="medium",
                help_text="Relative difficulty of the question",
                max_length=10,
            ),
        ),
    ]
