# Generated by Django 5.2.4 on 2025-11-23 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pastpapers", "0002_question_answer_text_question_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="starter_code",
            field=models.TextField(blank=True, default="# Write your code here"),
        ),
    ]
