# Generated by Django 5.2.4 on 2025-11-23 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pastpapers", "0003_question_starter_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="image_2",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="pastpapers/questions/%Y/%m/%d/",
                verbose_name="Second Image (Optional)",
            ),
        ),
    ]
