# Generated by Django 5.2.4 on 2025-12-05 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homework", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="source_template",
            field=models.ForeignKey(
                blank=True,
                help_text="Select a template to auto-fill fields",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="homework.homeworktemplate",
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="feedback",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="submission",
            name="grade",
            field=models.CharField(
                blank=True, help_text="e.g. A, 8/10, Pass", max_length=10
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "In Progress"),
                    ("submitted", "Submitted"),
                    ("graded", "Graded"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="code",
            field=models.TextField(blank=True),
        ),
    ]
