# Generated by Django 5.2.4 on 2026-01-18 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homework", "0002_assignment_source_template_submission_feedback_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="grade",
            field=models.CharField(
                blank=True, help_text="e.g. A, 7/10, Pass", max_length=10
            ),
        ),
        migrations.CreateModel(
            name="TestCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "input_text",
                    models.TextField(
                        blank=True, help_text="Input to provide to stdin (optional)"
                    ),
                ),
                (
                    "expected_output",
                    models.TextField(help_text="Expected output from stdout"),
                ),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_cases",
                        to="homework.assignment",
                    ),
                ),
            ],
        ),
    ]
