# Generated by Django 5.2.4 on 2026-01-18 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homework", "0003_alter_submission_grade_testcase"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="manual_review_requested",
            field=models.BooleanField(
                default=False,
                help_text="Student requested teacher review despite test failures",
            ),
        ),
    ]
